name: 'example'
description: 'Example project for the Automated Testing Framework.'
publish_to: 'none'
version: '1.0.0+6'

environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  automated_testing_framework_example: '^2.2.4+7'
  automated_testing_framework_plugin_images: '^4.0.0+6'
  flutter: 
    sdk: 'flutter'

dependency_overrides: 
  automated_testing_framework_plugin_github: 
    path: '../'


dev_dependencies: 
  flutter_launcher_icons: '^0.9.3'
  flutter_test: 
    sdk: 'flutter'

flutter_icons: 
  android: true
  ios: true
  image_path: 'assets-src/icon.png'

flutter_native_splash: 
  image: 'assets-src/splash.png'
  color: '212121'
  android_disable_fullscreen: true

flutter: 
  uses-material-design: true
  assets: 
    - 'assets/secrets/'
